### ISSUE TITLE
<uir-transitions-view></uir-transitions-view> didn't work

### ISSUE THREAD

**Issue by tigerxiong** [ui-router/visualizer#2]
Hi, I got a error when html load first time.
In my Chrome console, showes this message.
Cannot convert undefined or null to object
    at UirTransitionView.paramsForNode 
    at Array.map (native)

And uir-transitions-view directive, show raw code and didn't bind transition params.
Transition #{{::vm.trans.$id}}
From State:	{{::vm.trans.from().name || '(root)'}}
To State:	{{::vm.trans.to().name || '(root)'}}
Parameters:	
Outcome:	{{vm.status}}: {{vm.rejection}}
From Path	To Path

Can you give me some suggestions about what's going wrong.

**Comment by tigerxiong** [comment]
I use ui router instead of jspm's angular-ui-router@1.0.0-alpha0, and remove ui-router-extras,  then the problem fix.
I question is which ui router should I download by jspm.

**Comment by christopherthielen** [comment]
- ui-router-visualizer requires ui-router 1.0.0alpha0 or higher
- ui-router-extras is not yet compatible with ui-router 1.0+

It looks like jspm is fetching angular-ui-router from github.  That's a problem for 1.0 versions.  Try using `jspm install npm:angular-ui-router@1.0.0-alpha.4`

I'll see if I can get the jspm registry updated to use npm instead of github.

**Comment by tigerxiong** [comment]
I use ui-router-visualizer without hot css.
Then use angular-ui-router@1.0.0-alpha.4.
I didn't use ui router extras, it works and the ui router is the right version, maybe it integrates ui router extras in it.

**Comment by christopherthielen** [comment]
We just released 2.0.0 version of the visualizer.  It uses React and has a different bootstrap (but still works with any framework: Angular 1, 2 and React). 

This ticket is no longer valid, since there is no longer any angular directives. 

See the README.md for information on how to run the new React version.
